{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fnil\fcharset0 HelveticaNeue-Medium;\f1\fnil\fcharset0 HelveticaNeue-MediumItalic;}
{\colortbl;\red255\green255\blue255;\red38\green38\blue38;}
{\*\expandedcolortbl;;\cssrgb\c20000\c20000\c20000;}
\margl1440\margr1440\vieww14620\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs76 \cf2 \expnd0\expndtw0\kerning0
## Reproducible Research Project 1\
\pard\pardeftab720\partightenfactor0

\f1\i\fs36 \cf2 ## Dennis Oriaifo
\f0\i0 \

\f1\i ## June 11th, 2017\
\
rm(list=ls())\
cat("\\014")\
library(ggplot2)\
library(lattice)\
library(scales)\
library(Hmisc)\
library(dplyr)\
\
#Load Dataset\
dataset = read.csv("activity.csv", header = TRUE, sep = ',', colClasses = c("numeric", "character","integer"))\
dataset = transform(dataset, date = as.Date(dataset$date, format = "%Y-%m-%d"))\
\
ggplot(data = na.omit(dataset), aes(date, steps)) + stat_summary(fun.y = sum, geom = "bar",fill='#16a085') +\
  labs(title = "Histogram of Steps per Day", x = "Steps per Day", y = "Frequency")\
\
daySteps = with(dataset, tapply(steps, date, sum, na.rm = TRUE))\
dayStepsMedian = median(daySteps)\
dayStepsMean = mean(daySteps)\
\
# What is the average daily dataset pattern?\
datasetForMeans = na.omit(dataset)\
datasetdMeans = with(datasetForMeans, tapply(steps, interval, mean))\
\
dayStepsAvg = aggregate(list(steps = dataset$steps), list(interval = dataset$interval), mean, na.rm = TRUE)\
\
ggplot(dayStepsAvg, aes(interval, steps)) + geom_line(color='#16a085') + xlab("Time Interval") +\
  ylab("Avg. Steps") + ggtitle("Avg. Activity Pattern") \
\
\
datasetAllMissing = sum(is.na(dataset$steps))\
sum(is.na(dataset$steps))/nrow(dataset)\
\
# Imputing missing values\
datasetMissing=length(which(is.na(dataset$steps)))\
datasetComplete = dataset\
datasetComplete$steps = impute(dataset$steps, fun=mean)\
\
plot3 = ggplot(data = dataset, aes(date, steps)) + stat_summary(fun.y = sum, geom =  'bar',fill='#16a085')\
plot3\
\
steps = with(dataset, tapply(steps, date, sum, na.rm = TRUE))\
mean(steps)\
\
# Are there differences in dataset patterns between datasetwkd and datasetwke?\
datasetwkd = c("Mon", "Tue", "Wed", "Thur", "Fri")\
datasetComplete = mutate(datasetComplete, weektype = ifelse(weekdays(datasetComplete$date) == "Saturday" | weekdays(datasetComplete$date) == "Sunday", "weekend", "weekday"))\
datasetComplete$weektype = as.factor(datasetComplete$weektype)\
head(datasetComplete)\
\
interval_full = datasetComplete %>% group_by(interval, weektype) %>% summarise(steps = mean(steps))\
plot4 = ggplot(interval_full, aes(x=interval, y=steps, color = weektype)) +\
  geom_line() + facet_wrap(~weektype, ncol = 1, nrow=2)\
plot4\
}